/* === ats-animations.js === */
/******* Do not edit this file *******
Simple Custom CSS and JS - by Silkypress.com
Saved: Mar 27 2026 | 12:41:45 */
(function() {
  var initAnimations = function() {
    var options = {
      root: null,
      rootMargin: '0px',
      threshold: 0.2
    };

    var handleIntersect = function(entries, observer) {
      entries.forEach(function(entry) {
        if (entry.isIntersecting) {
          entry.target.classList.add('is-visible');
          observer.unobserve(entry.target);
        }
      });
    };

    var observer = new IntersectionObserver(handleIntersect, options);
    var animateElements = document.querySelectorAll('.lp-animate');
    animateElements.forEach(function(el) { observer.observe(el); });
  };

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initAnimations);
  } else {
    initAnimations();
  }
})();

/* === ats-cats-gallery.js === */
/******* Do not edit this file *******
Simple Custom CSS and JS - by Silkypress.com
Saved: Mar 27 2026 | 12:42:54 */
document.addEventListener("DOMContentLoaded", () => {
  // Cats Gallery Tabs
  const catNavItems = document.querySelectorAll('.ats-cat-nav-item');
  
  catNavItems.forEach(navItem => {
      navItem.addEventListener('click', () => {
          const targetId = navItem.getAttribute('data-target');
          if (!targetId) return;

          // 1. Nav Active Toggle
          catNavItems.forEach(item => item.classList.remove('active'));
          navItem.classList.add('active');

          // 2. Panel Active Toggle
          const allPanels = document.querySelectorAll('.ats-cat-panel');
          allPanels.forEach(panel => {
              panel.classList.remove('active');
          });

          const targetPanel = document.getElementById(targetId);
          if (targetPanel) {
              targetPanel.classList.add('active');
          }
      });
  });
});

/* === ats-smooth-scroll.js === */
/******* Do not edit this file *******
Simple Custom CSS and JS - by Silkypress.com
Saved: Mar 27 2026 | 12:45:20 */


document.addEventListener("DOMContentLoaded", () => {

    
    const anchors = document.querySelectorAll('a[href^="#js-ats-access"]');
    
    anchors.forEach(function(anchor) {
        anchor.addEventListener('click', function(e) {
            // 移動先を取得
            const href = anchor.getAttribute('href');
            const target = document.querySelector(href);
            
            // 移動先が存在する場合のみ実行
            if (target) {
                e.preventDefault(); // デフォルトのガタッと飛ぶ挙動を防ぐ
                target.scrollIntoView({
                    behavior: 'smooth' // ここで滑らかなスクロールを指定
                });
            }
        });
    });


    
    // 監視のオプション設定（画面の10%が入ったら発火）
    const observerOptions = {
        root: null,
        rootMargin: "0px",
        threshold: 0.1 
    };

    // 監視時の動作定義
    const observer = new IntersectionObserver((entries, observer) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                // 画面に入ったらクラスを付与してアニメーション開始
                entry.target.classList.add('ats-active');
                // 一度表示したら監視をやめる（負荷軽減）
                observer.unobserve(entry.target); 
            }
        });
    }, observerOptions);

    // 監視対象(.ats-scroll-fade)をすべて取得して監視開始
    const targets = document.querySelectorAll('.ats-scroll-fade');
    targets.forEach(target => observer.observe(target));


    
    const track = document.getElementById('atsReviewTrack');
    const prevBtn = document.getElementById('atsReviewPrev');
    const nextBtn = document.getElementById('atsReviewNext');

    // 要素が存在する場合のみ実行（エラー防止）
    if (track && prevBtn && nextBtn) {
        let currentIndex = 0;
        const slides = Array.from(track.children);

        // スライド位置を更新する関数
        const updateSlidePosition = () => {
            // スライド1枚分の幅を取得して移動距離を計算
            const slideWidth = slides[0].getBoundingClientRect().width;
            track.style.transform = 'translateX(-' + (slideWidth * currentIndex) + 'px)';
        };

        // 表示枚数の判定（PCなら3枚、スマホなら1枚）
        const getVisibleSlides = () => {
            if (window.innerWidth >= 768) {
                return 3;
            }
            return 1;
        };

        // 「次へ」ボタンクリック時
        nextBtn.addEventListener('click', () => {
            const visibleSlides = getVisibleSlides();
            const maxIndex = slides.length - visibleSlides; // 最大インデックス（これ以上右に行けない位置）

            if (currentIndex < maxIndex) {
                currentIndex++;
            } else {
                currentIndex = 0; // 最後まで行ったら最初に戻る（ループ）
            }
            updateSlidePosition();
        });

        // 「前へ」ボタンクリック時
        prevBtn.addEventListener('click', () => {
            const visibleSlides = getVisibleSlides();
            const maxIndex = slides.length - visibleSlides;

            if (currentIndex > 0) {
                currentIndex--;
            } else {
                currentIndex = maxIndex; // 最初から前に行ったら最後へ（ループ）
            }
            updateSlidePosition();
        });

        // 画面リサイズ時に位置ズレを直す
        window.addEventListener('resize', () => {
            updateSlidePosition();
        });
    }
	// 3. Story Section Tabs (Desktop)
  const storyItems = document.querySelectorAll('.ats-story-item');
  
  storyItems.forEach(item => {
    item.addEventListener('click', (e) => {
      // Check if mobile (pointer-events: none set in CSS handles this mostly, but good to be safe)
      if (window.innerWidth <= 767) return;

      const targetId = item.getAttribute('data-target');
      const groupName = item.parentElement.getAttribute('data-group');
      if (!targetId || !groupName) return;

      // Reset active state for items in same group
      const groupItems = document.querySelectorAll(`.ats-story-list[data-group="${groupName}"] .ats-story-item`);
      groupItems.forEach(gi => gi.classList.remove('active'));

      // Add active state to clicked
      item.classList.add('active');

      // Update Visual
      const groupVisuals = document.querySelectorAll(`.ats-story-visual[data-group="${groupName}"] .ats-story-img`);
      groupVisuals.forEach(gv => gv.classList.remove('active'));

      const targetVisual = document.getElementById(targetId);
      if (targetVisual) {
        targetVisual.classList.add('active');
      }
    });
  });

});

/* === lp-voice-modal.js === */
/******* Do not edit this file *******
Simple Custom CSS and JS - by Silkypress.com
Saved: Mar 27 2026 | 12:24:23 */
document.addEventListener('DOMContentLoaded', function() {
  var modal = document.querySelector('.lp-modal-overlay');
  var closeBtn = document.querySelector('.lp-modal-close-btn');
  var modalImg = document.querySelector('.lp-modal-content');
  var items = document.querySelectorAll('.lp-voice-item');

  if (!modal || !closeBtn || !modalImg) return;

  // 画像クリックでモーダルを開く
  items.forEach(function(item) {
    item.addEventListener('click', function() {
      var img = item.querySelector('img');
      if (img) {
        modalImg.src = img.src;
        modalImg.style.display = 'block'; // 画像を表示
        modal.classList.add('active');
      }
    });
  });

  // モーダルを閉じる処理
  function closeMyModal() {
    modal.classList.remove('active');
    setTimeout(function(){ 
      modalImg.src = ''; 
      modalImg.style.display = 'none'; // 画像を非表示に
    }, 300);
  }

  closeBtn.addEventListener('click', function(e) {
    e.stopPropagation();
    closeMyModal();
  });

  modal.addEventListener('click', function(e) {
    if (e.target === modal) {
      closeMyModal();
    }
  });
});

